<?php
/**
 * Created by PhpStorm.
 * User: Egidijus
 * Date: 12/9/2016
 * Time: 1:36 PM
 */

namespace AppBundle\Form;



use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class SignupForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name_surname', TextType::class,array(
            'label'=>'Vardas Pavardė*'
        ))
        ->add('email',EmailType::class,array(
            'label'=> 'El.paštas*'
        ))
        ->add('phone_number',TextType::class,array(
            'label'=> 'Telefono Numeris*',
            'required'=> false
        ))
        ->add('password', RepeatedType::class, array(
            'type'=>PasswordType::class,
            'invalid_message' => 'Slaptažodžių laukai turi sutapti.',
            'options' => array('attr' => array('class' => 'password-field')),
            'required' => true,
            'first_options'=> array('label'=>'Slaptažodis'),
            'second_options'=> array('label'=>'Pakartoti Slaptažodį'),
        ))
        ->add('submit', SubmitType::class,array(
            'label'=> 'REGISTRUOTIS'
        ));

        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'=>'AppBundle\Entity\DatabaseUserVariables'
        ));
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}